# Tensors
Tensors are a specialized data structure that are very similar to arrays and matrices.

In [2]:
# import libraries
import torch
import numpy as np

## Tensor initialization
How to initialized tensor

In [6]:
# directly from data
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

print(x_data, type(x_data))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [7]:
# from a numpy array
np_array = np.array(data)
x_np = torch.tensor(np_array)

print(x_data, type(x_data))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [11]:
# from another tensor
x_ones = torch.zeros_like(x_data) # retains the properties of x_data
print(f"Zeros Tensor: \n {x_ones}")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatypes of x_data
print(f"Random Tensor: \n {x_rand}")

Zeros Tensor: 
 tensor([[0, 0],
        [0, 0]])
Random Tensor: 
 tensor([[0.1483, 0.4599],
        [0.1456, 0.2741]])


In [17]:
# with random or constant values
shape = (3, 4)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros((3, 4))

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9689, 0.8185, 0.5480, 0.0340],
        [0.1292, 0.2438, 0.2219, 0.3153],
        [0.3384, 0.8916, 0.3431, 0.6742]]) 

Ones Tensor: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


## Tensor Attributes
Tensor attributes describe their shape, datatype, and the device on which they are stored

In [22]:
tensor = torch.zeros((2, 3,))

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([2, 3])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Tensor Operations


In [84]:
# standard numpy-like indexing and slicing
tensor = torch.ones(4, 4)
tensor[:, [1, 2]] = 0

print(tensor)

tensor([[1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.]])


In [85]:
# joining tensors
t1 = torch.cat([tensor, tensor], dim=0) # dim=0 joining rows, dim=1 joining columns
print(t1)

tensor([[1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.]])


In [86]:
# multiplying tensors (element-wise product)
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)}")

tensor.mul(tensor) 
 tensor([[1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.]])


In [87]:
# matrix multiplication
print(f"tensor.mul(tensor) \n {tensor.matmul(tensor.T)}")

# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.mul(tensor) 
 tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])
tensor @ tensor.T 
 tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])


In [88]:
# in-place operations 
tensor.add_(2)
print(tensor)

tensor([[3., 2., 2., 3.],
        [3., 2., 2., 3.],
        [3., 2., 2., 3.],
        [3., 2., 2., 3.]])


## Bridge with Numpy

In [91]:
# tensor to numpy array
t = torch.zeros(5,)
print(t, type(t))
n = t.numpy()
print(n, type(n))

tensor([0., 0., 0., 0., 0.]) <class 'torch.Tensor'>
[0. 0. 0. 0. 0.] <class 'numpy.ndarray'>


In [92]:
# numpy array to tensor
n = np.ones(4,)
print(n, type(n))
t = torch.from_numpy(n)
print(t)

[1. 1. 1. 1.] <class 'numpy.ndarray'>
tensor([1., 1., 1., 1.], dtype=torch.float64)


In [93]:
# change numpy array reflects in the tensor
np.add(n, 2, out=n)
print(n)
print(t)

[3. 3. 3. 3.]
tensor([3., 3., 3., 3.], dtype=torch.float64)
